// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestJwt.Data;

#nullable disable

namespace TestJwt.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    [Migration("20241031162540_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestJwt.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$11$k9O8w.Ak1zZUcegqUX9fw.059Eyw2RxBohXHpEtYG9B3kSgIHkJLy",
                            RefreshToken = "5eb22269-0a4c-496d-b6d8-bdc6925c892e",
                            RefreshTokenExpiryTime = new DateTime(2024, 11, 7, 19, 55, 39, 692, DateTimeKind.Local).AddTicks(2783),
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "$2a$11$B.IWkNcA/x0aflMLAjqAeeF9RAAX.4ITiDvl62/hNzCzCdgw6CxK2",
                            RefreshToken = "d0bc566d-f529-4724-ac81-299d7c0771a8",
                            RefreshTokenExpiryTime = new DateTime(2024, 11, 7, 19, 55, 39, 860, DateTimeKind.Local).AddTicks(3799),
                            Role = "User",
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
